# Generated by Django 5.2.14 on 2026-05-26 20:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoMultipartUpload",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("s3_upload_id", models.CharField(max_length=128)),
                ("s3_bucket", models.CharField(max_length=128)),
                ("s3_key", models.CharField(max_length=512)),
                ("total_parts", models.IntegerField(blank=True, null=True)),
                ("uploaded_parts", models.JSONField(default=list)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="multipart_upload", to="videos.video"
                    ),
                ),
            ],
            options={
                "db_table": "video_multipart_uploads",
            },
        ),
    ]
