# Generated by Django 5.2.14 on 2026-05-26 20:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploaderProfile",
            fields=[
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                ("display_name", models.CharField(max_length=128)),
                ("avatar_url", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "uploader_profiles",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("uploader_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("category", models.CharField(blank=True, max_length=64)),
                ("age_rating", models.CharField(blank=True, max_length=8)),
                ("raw_s3_key", models.CharField(blank=True, max_length=512)),
                ("raw_file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("hls_manifest_url", models.TextField(blank=True)),
                ("dash_manifest_url", models.TextField(blank=True)),
                ("thumbnail_url", models.TextField(blank=True)),
                ("sprite_url", models.TextField(blank=True)),
                ("available_qualities", models.JSONField(blank=True, default=list)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_live", models.BooleanField(default=False)),
                ("view_count", models.BigIntegerField(default=0)),
                ("average_rating", models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ("rating_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "videos",
                "indexes": [
                    models.Index(fields=["-published_at"], name="idx_videos_published"),
                    models.Index(fields=["category", "-published_at"], name="idx_videos_category"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TranscodeJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("mediaconvert_job_id", models.CharField(blank=True, max_length=128)),
                ("attempts", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transcode_jobs", to="videos.video"
                    ),
                ),
            ],
            options={
                "db_table": "transcode_jobs",
            },
        ),
    ]
