# Generated by Django 6.0.5 on 2026-06-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="live_session_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
