# Generated by Django 5.2.14 on 2026-05-26 10:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionTier",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[("free_trial", "Free Trial"), ("basic", "Basic"), ("premium", "Premium")],
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("max_quality", models.CharField(max_length=8)),
                ("simultaneous_streams", models.PositiveSmallIntegerField(default=1)),
                ("can_download", models.BooleanField(default=False)),
                ("price_monthly_usd", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                "db_table": "subscription_tiers",
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                            ("incomplete", "Incomplete"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("trial_start", models.DateTimeField(blank=True, null=True)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("stripe_subscription_id", models.CharField(blank=True, db_index=True, max_length=128)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tier",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="subscriptions.subscriptiontier"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_subscriptions",
                "indexes": [
                    models.Index(fields=["user"], name="user_subscr_user_id_3bc394_idx"),
                    models.Index(
                        condition=models.Q(("status", "trialing")),
                        fields=["trial_end"],
                        name="idx_subscriptions_trial_end",
                    ),
                ],
            },
        ),
    ]
